apiVersion: v1
kind: Service
metadata:
  name: houseinv-service
spec:
  type: LoadBalancer
  selector:
    app: houseinv
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: houseinv-deployment
spec:
  selector:
    matchLabels:
      app: houseinv
  template:
    metadata:
      labels:
        app: houseinv
    spec:
      containers:
      - name: houseinv
        image: ksmrva/houseinv:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
        env:
          - name: MongoDbConfig__Host
            value: mongodb-service
          - name: MongoDbConfig__Password
            valueFrom:
              secretKeyRef:
                name: data
                key: mongodb-password
          - name: PostgresConfig__Host
            value: postgres-service
          - name: PostgresConfig__Password
            valueFrom:
              secretKeyRef:
                name: data
                key: postgres-password
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
